config/routes.rb
Superzapatos::Application.routes.draw do
  resources :articles

  resources :stores

  root :to => "stores#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js, :xml, :json

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @count = 0
    for i in @articles
      @count = @count+1
    end
    respond_with @articles do |format|
      #format.json { render json: { "Articles" => @articles.as_json(:except => [:created_at,:updated_at], :root => false) }.to_json}
      format.json { render json: { "Articles" => @articles.as_json(:except => [:created_at,:updated_at], :root => false),
        "Total_elements" =>  @count.as_json,
        "Successs" => true}.to_json}
      format.xml  { render :xml => @articles.to_xml(:except => [:created_at,:updated_at])} 
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js, :xml, :json
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    @count = 0
    for i in @stores
      @count = @count+1
    end
    respond_with @stores do |format|
      #format.json { render :text => @stores.to_json(:only => [ :id, :name ]) }
      format.json { render json: { "Stores" => @stores.as_json(:except => [:created_at,:updated_at],:root => false),
      "Total_elements" =>  @count.as_json,
      "Successs" => true }.to_json}
      format.xml  { render :xml => @stores.to_xml(:except => [:created_at,:updated_at])}  
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @stores = Store.find(params[:id])
    @articles = @stores.articles
    @count = 0
    for i in @articles
      @count = @count+1
    end
    respond_with @stores do |format|
      format.json { render json: {"Articles" => @articles.as_json(:except => [:created_at,:updated_at], :root => false),
        "Total_elements" =>  @count.as_json,
        "Successs" => true}.to_json}
      #format.json { render json: {"Store" => @stores.as_json(:only => [:name], :root => false)}.to_json}
      format.xml  { render :xml => @articles.to_xml(:except => [:created_at,:updated_at])} 
    end
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total_in_shelf, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_in_shelf, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total_in_vault, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_in_vault, :class => 'text_field' %>
    </div>
  </div>
  <!--
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_id, :class => 'text_field' %>
    </div>
  </div>
  -->

  <div class="control-group">
    <%= f.label :stores_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :store_id, Store.all, :id, :name %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:total_in_shelf) %></th>
      <th><%= model_class.human_attribute_name(:total_in_vault) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= article.store_id %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @article.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @article.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @article.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_in_shelf) %>:</strong></dt>
  <dd><%= @article.total_in_shelf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_in_vault) %>:</strong></dt>
  <dd><%= @article.total_in_vault %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_id) %>:</strong></dt>
  <dd><%= @article.store_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Superzapatos" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Superzapatos</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Stores", stores_path()  %></li>
              <li><%= link_to "All Articles", articles_path  %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">JSON Format <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Stores In Json", stores_path(format: :json) %></li>
                  <li><%= link_to "Articles In Json", articles_path(format: :json) %></li>
                  <li><%= link_to "One Article In Json", store_path(:id => 1,format: :json) %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">XML Format <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Stores In XML", stores_path(format: :xml)  %></li>
                  <li><%= link_to "Articles In XML", articles_path(format: :xml)%></li>
                  <li><%= link_to "One Article In XML", store_path(:id => 1,format: :xml) %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        </br></br>
        <p>&copy; SuperZapatos 2013</p>
        <p>Created by Sergio Monge</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=@store.name %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_path(@store), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_path(@store),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @store.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @store.address %></dd>
</dl>

<div>
<h3>Articles in this store</h3>
  <table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:total_in_shelf) %></th>
      <th><%= model_class.human_attribute_name(:total_in_vault) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= article.store_id %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path, :class => 'btn btn-mini btn-default' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>